server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/screw?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            clientId: 'c4957dae238f06a38023a0dc6d8a3470'
            client-secret: 'w6kaWJJfKcyRdztikP6iUHjH1iQD8M6Y'
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
              - profile_image
            client-name: Kakao
            client-authentication-method: POST

          google:
            clientId: '172277634523-98tafp4js0ak28gmctajdeu3hl6vr8pn.apps.googleusercontent.com'
            clientSecret: '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'
            redirect-uri: http://localhost:8081/login/oauth2/code/google
            scope:
              - email
              - profile

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug